version: '3.8'

services:
  chatapp:
    build: .
    image: chatapp:latest
    container_name: chatapp
    ports:
      - "8080:8080"
    #    volumes:
    #      - ./target/classes:/app/classes
    #      - ./src/main/resources/static:/app/static
    environment:
      # PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatapp_kszh
      SPRING_DATASOURCE_USERNAME: chatapp_kszh_user
      SPRING_DATASOURCE_PASSWORD: 4ffQGw3dq6vbwmPIIC3nr5Pah6NotIfS
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: chatapp_db
    environment:
      POSTGRES_DB: chatapp_kszh
      POSTGRES_USER: chatapp_kszh_user
      POSTGRES_PASSWORD: 4ffQGw3dq6vbwmPIIC3nr5Pah6NotIfS
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
