# === DATABASE ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/chatapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chatuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chatpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.period=0

spring.devtools.restart.include=static/**,public/**,resources/**,META-INF/resources/**
