spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/chatapp_kszh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chatapp_kszh_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:4ffQGw3dq6vbwmPIIC3nr5Pah6NotIfS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}
# fallback 8080 dla lokalnego uruchomienia


spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.period=0

spring.devtools.restart.include=static/**,public/**,resources/**,META-INF/resources/**
